### ISSUE TITLE
Update for NB8.1?

### ISSUE THREAD

**Issue by Gittino** [junichi11/netbeans-change-lf#15]
Hi,
is this plugin still supported? 
If yes for when is planned the release of the version compatible with NB 8.1? 
Thanks in advence
Best regards.

**Comment by junichi11** [comment]
Hi, 

I'll publish it later.

Thanks.

**Comment by junichi11** [comment]
Done.

https://github.com/junichi11/netbeans-change-lf/releases/tag/v0.6.0 or http://plugins.netbeans.org/plugin/46829/change-line-endings-on-save

**Comment by Gittino** [comment]
Thanks a lot for your quick answer and obviously for the useful plugin.
Best regards

**Comment by junichi11** [comment]
You are welcome :)
