### ISSUE TITLE
Update needed for Netbeans 8.2

### ISSUE THREAD

**Issue by Gittino** [junichi11/netbeans-change-lf#16]
Hi could you update this plugin so that it works with the new version of Netbeans (8.2) ?
Thanks and best regards

**Comment by junichi11** [comment]
No changes (just rebuild with NetBeans 8.2)

https://github.com/junichi11/netbeans-change-lf/releases/tag/v0.6.0 (com-junichi11-netbeans-changelf-0.6.0-nb82.nbm)

Thanks.
