### ISSUE TITLE
Verify Certificate

### ISSUE THREAD

**Issue by lynnellemmanuel** [junichi11/netbeans-change-lf#20]
Hello. I am installing in with my NetBeans 8.2 when I am prompted in verifying the certificate.
![verify-certificate-line-ending](https://user-images.githubusercontent.com/7625546/32726854-6b2a397e-c8b5-11e7-9f75-820bce7665cb.PNG)

I'm sorry but I'm a newbie when it comes to certificate things. What should I do? Should I trust this? I downloaded it in NetBeans Plugin portal.

**Comment by junichi11** [comment]
If there is no problem when you look at "Show details", just click "continue". When we install third-party plugins, this dialog is always shown.

**Comment by lynnellemmanuel** [comment]
I see. Thank you so much. And yes, the plugin works fine. Super useful.
