### ISSUE TITLE
The plugin seems to do nothing on NetBeans 10.0

### ISSUE THREAD

**Issue by naitsirch** [junichi11/netbeans-change-lf#21]
I can change the setting to enable the adjustment of line endings. But when I open the options dialogue again, the option is disabled again.

And after saving the file, line endings are still with CRLR :-(

**Comment by junichi11** [comment]
I've rebuilt the plugin in NetBeans 10.0. https://github.com/junichi11/netbeans-change-lf/releases/tag/v0.7.0
Please give it a try. Thanks.
