### ISSUE TITLE
Plugin link in About section doesn't work

### ISSUE THREAD

**Issue by MCEmperor** [junichi11/netbeans-change-lf#25]
On the _About_ section in the right panel under the _Code_ tab in GitHub, the link to the plugin page (http://plugins.netbeans.org/plugin/46829/change-line-endings-on-save) doesn't work anymore. It seems to be migrated to https://plugins.netbeans.apache.org/catalogue/?id=31.

**Comment by junichi11** [comment]
Thank you for letting me know :)
Fixed.
